services:

  # Database
  db:
    image: ${WORDPRESS_SQL_IMAGE_TAG}
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ADMIN_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks: 
      - wpsite
    
  # PhpMyAdmin
  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - '8080:80'
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ADMIN_PASSWORD}
    networks: 
      - wpsite

  wordpress:
    depends_on:
      - db
    build:
      context: .
      args:
        WORDPRESS_IMAGE_TAG: ${WORDPRESS_IMAGE_TAG}
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    volumes:
      - './:/var/www/html'
    networks: 
      - wpsite

networks:
  wpsite: 
volumes:
  db_data: {}